EXERCISE 1 ■ Test scores
Create a series of 10 elements, random integers from 70 to 100, representing scores on a monthly exam. Set the index to be the month names, starting in September and ending in June. (If these months don’t match the school year in your location, feel free to make them more realistic.)

With this series, write code to answer the following questions:
1. What is the student’s average test score for the entire year?
2. What is the student’s average test score during the first half of the year (i.e., the first five months)?
3. What is the student’s average test score during the second half of the year?
4. Did the student improve their performance in the second half? If so, by how much?

In [9]:
import pandas as pd
import numpy as np

In [27]:
g = np.random.default_rng(0)
a = g.integers(0, 100, 10)
a

array([85, 63, 51, 26, 30,  4,  7,  1, 17, 81])

In [34]:
g = np.random.default_rng(0)
b = g.integers(0, 100, 10)
b

array([85, 63, 51, 26, 30,  4,  7,  1, 17, 81])

In [35]:
a == b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [36]:
# Creating a series
g = np.random.default_rng(0)
s = pd.Series(g.integers(70, 101, 10))
s

0    96
1    89
2    85
3    78
4    79
5    71
6    72
7    70
8    75
9    95
dtype: int64

In [37]:
# s.index = 'Sep Oct Nov Dec Jan Feb Mar Jun Jul Aug'.split()
# s

Sep    96
Oct    89
Nov    85
Dec    78
Jan    79
Feb    71
Mar    72
Jun    70
Jul    75
Aug    95
dtype: int64

In [39]:
# packing everything together.
g = np.random.default_rng(0)
months = 'Sep Oct Nov Dec Jan Feb Mar Apr May Jun'.split()
s = pd.Series(g.integers(70, 101, 10), index=months)
s

Sep    96
Oct    89
Nov    85
Dec    78
Jan    79
Feb    71
Mar    72
Apr    70
May    75
Jun    95
dtype: int64

In [40]:
# Yearly mean
print(f'Yearly average: {s.mean()}')

Yearly average: 81.0


In [41]:
# first and second half average calculations
first_half_average = s['Sep':'Jan'].mean()
second_half_average = s['Feb':'Jun'].mean()
print(f'Improvement: {second_half_average - first_half_average}')

Improvement: -8.800000000000011
