## The basics of NumPy arrays

### NumPy array attributes

In [2]:
import numpy as np

rng = np.random.default_rng(seed=1701)  # seed for reproducibility

x1 = rng.integers(10, size=6)  # one-dimensional array
x2 = rng.integers(10, size=(3, 4))  # two-dimensional array
x3 = rng.integers(10, size=(3, 4, 5))  # three-dimensional array

In [5]:
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)
print("x3 dtype:", x3.dtype)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60
x3 dtype: int64


### Array Indexing: Accessing Single elements

In [6]:
x1

array([9, 4, 0, 3, 8, 6])

In [7]:
x1[0]

9

In [8]:
x1[4]

8

In [9]:
x1[-1]

6

In [10]:
x1[-2]

8

In [11]:
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]])

In [14]:
x2[0, 0]

3

In [15]:
x2[2, 0]

0

In [16]:
x2[2, -1]

9

In [17]:
x2[0, 0] = 12

In [18]:
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]])

In [19]:
x1[0] = 3.14159 # This will be truncated.
x1

array([3, 4, 0, 3, 8, 6])

### Array Slicing:Accessing Subarrays

#### One-Dimensional Arrays

In [20]:
x1

array([3, 4, 0, 3, 8, 6])

In [22]:
x1[:3]

array([3, 4, 0])

In [23]:
x1[3:]

array([3, 8, 6])

In [24]:
x1[1:4]

array([4, 0, 3])

In [25]:
x1[::2]  # Every second element

array([3, 0, 8])

In [26]:
x1[1::2] # Every second element starting index 1

array([4, 3, 6])

#### Multidimensional Subarrays

In [27]:
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]])

In [28]:
x2[:2, :3]  # first two rows and three columns

array([[12,  1,  3],
       [ 4,  0,  2]])

In [29]:
x2[:3, ::2]  # three rows, every second column

array([[12,  3],
       [ 4,  2],
       [ 0,  6]])

In [30]:
x2[::-1, ::-1]  # all rows & columns reversed

array([[ 9,  6,  0,  0],
       [ 3,  2,  0,  4],
       [ 7,  3,  1, 12]])

In [31]:
x2[0, :]  # First row of x2

array([12,  1,  3,  7])

In [32]:
x2[0]  # Equivalent of x2[0, :]

array([12,  1,  3,  7])