In [1]:
import numpy as np
rng = np.random.default_rng(seed=1701)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = rng.integers(1, 10, size=5)
compute_reciprocals(values=values)

array([0.11111111, 0.25      , 1.        , 0.33333333, 0.125     ])

In [2]:
# Lets do the same for big array
big_array = rng.integers(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

1.01 s ± 10.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### Introducing Ufuncs

In [6]:
print(compute_reciprocals(values=values))
print(1.0 / values)

[0.11111111 0.25       1.         0.33333333 0.125     ]
[0.11111111 0.25       1.         0.33333333 0.125     ]


In [7]:
%timeit (1.0 / big_array)

1.05 ms ± 3.41 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [8]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [9]:
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

### Exploring NumPy's Ufuncs

#### Array Arithmetic

In [11]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
