#### Introduction to NumPy

In [2]:
import numpy as np

#### Datatypes and Attributes

In [3]:
## Numpy main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

In [6]:
a2.ndim

2

In [7]:
a1.ndim

1

In [8]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],

               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [9]:
a3.ndim

3

In [10]:
a3.shape

(2, 3, 3)

In [11]:
# lets create an array with shape (2, 4, 5)
test_array = np.array([[[1, 2, 3, 4, 5],
                        [6, 7, 8, 9, 1],
                        [2, 3, 4, 5, 6],
                        [7, 8, 9, 1, 2]],
                        
                        [[1, 2, 3, 4, 5],
                         [6, 7, 8, 9, 1],
                         [2, 3, 4, 5, 6],
                         [7, 8, 9, 1, 2]]])

In [12]:
test_array.ndim

3

In [13]:
test_array.shape

(2, 4, 5)

In [14]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [15]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [16]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [17]:
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (2, 3, 3))

In [18]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [19]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [20]:
# Create a pandas dataframe from numpy array
import pandas as pd

In [21]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [22]:
# df_3 = pd.DataFrame(a3)  # We cannot visualize this.

#### Creating Arrays

In [23]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [24]:
sample_array.dtype

dtype('int64')

In [25]:
ones = np.ones((2, 3, 4))
ones

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [26]:
ones.dtype

dtype('float64')

In [27]:
type(ones)

numpy.ndarray

In [28]:
zeros = np.zeros((2, 3, 4))
zeros

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [29]:
zeros.dtype

dtype('float64')

In [30]:
type(zeros)

numpy.ndarray

In [31]:
range_array = np.arange(0, 10, 2) # start stop step
range_array

array([0, 2, 4, 6, 8])

In [32]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[2, 4, 2, 2, 1],
       [7, 3, 9, 5, 2],
       [3, 5, 4, 6, 0]])

In [33]:
# One more way to create random array
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.04339021, 0.68202681, 0.05516909],
       [0.9885464 , 0.98094381, 0.91454254],
       [0.12362249, 0.40310415, 0.27866607],
       [0.30172729, 0.95943737, 0.41973759],
       [0.97770452, 0.00540274, 0.40390309]])

In [34]:
random_array_2.shape

(5, 3)

In [35]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.71177676, 0.21477144, 0.55278616],
       [0.7653303 , 0.19863665, 0.03594711],
       [0.08345933, 0.80177119, 0.45340426],
       [0.9277846 , 0.60572169, 0.33075996],
       [0.7549476 , 0.93353552, 0.60146188]])

In [36]:
# Psuedo random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [37]:
random_array_4.shape

(5, 3)

In [38]:
np.random.seed(seed=7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [39]:
random_array_6 = np.random.random((5, 3))
random_array_6

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

### Viewing Arrays and Matrices

In [40]:
# Finding unique values in an array
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.unique(random_array_6)

array([0.02489923, 0.13316945, 0.21338535, 0.23030288, 0.45212396,
       0.46775286, 0.52341258, 0.54848992, 0.60054892, 0.66901324,
       0.75040986, 0.90912837, 0.90959353, 0.93120602, 0.9501295 ])

In [42]:
a1

array([1, 2, 3])

In [43]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [44]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [45]:
a1[0]

1

In [46]:
a2.shape

(2, 3)

In [47]:
a2[0]

array([1. , 2. , 3.3])

In [48]:
a3.shape

(2, 3, 3)

In [49]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
a2.shape, a2

((2, 3),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]))

In [51]:
a2[1]

array([4. , 5. , 6.5])

In [52]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [53]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [54]:
a3[:1, :2, :2]

array([[[1, 2],
        [4, 5]]])

In [55]:
# We will create 4 dimensional array
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]])

In [56]:
# slicing the required array from the matrix of multiple dimensions.
a4[0, 2, 0]

array([8, 6, 7, 2, 7])

In [57]:
a4.shape

(2, 3, 4, 5)

In [58]:
a4[:, :, :, :1]

array([[[[6],
         [0],
         [5],
         [1]],

        [[9],
         [3],
         [3],
         [4]],

        [[8],
         [3],
         [6],
         [4]]],


       [[[6],
         [4],
         [1],
         [5]],

        [[9],
         [5],
         [9],
         [6]],

        [[0],
         [4],
         [7],
         [5]]]])