#### Introduction to NumPy

In [70]:
import numpy as np

#### Datatypes and Attributes

In [71]:
## Numpy main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [72]:
type(a1)

numpy.ndarray

In [73]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

In [74]:
a2.ndim

2

In [75]:
a1.ndim

1

In [76]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],

               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [77]:
a3.ndim

3

In [78]:
a3.shape

(2, 3, 3)

In [79]:
# lets create an array with shape (2, 4, 5)
test_array = np.array([[[1, 2, 3, 4, 5],
                        [6, 7, 8, 9, 1],
                        [2, 3, 4, 5, 6],
                        [7, 8, 9, 1, 2]],
                        
                        [[1, 2, 3, 4, 5],
                         [6, 7, 8, 9, 1],
                         [2, 3, 4, 5, 6],
                         [7, 8, 9, 1, 2]]])

In [80]:
test_array.ndim

3

In [81]:
test_array.shape

(2, 4, 5)

In [82]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [83]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [84]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [85]:
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (2, 3, 3))

In [86]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [87]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [88]:
# Create a pandas dataframe from numpy array
import pandas as pd

In [89]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [90]:
# df_3 = pd.DataFrame(a3)  # We cannot visualize this.

#### Creating Arrays

In [91]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [92]:
sample_array.dtype

dtype('int64')

In [93]:
ones = np.ones((2, 3, 4))
ones

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [94]:
ones.dtype

dtype('float64')

In [95]:
type(ones)

numpy.ndarray

In [96]:
zeros = np.zeros((2, 3, 4))
zeros

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [97]:
zeros.dtype

dtype('float64')

In [98]:
type(zeros)

numpy.ndarray

In [99]:
range_array = np.arange(0, 10, 2) # start stop step
range_array

array([0, 2, 4, 6, 8])

In [100]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[1, 1, 5, 3, 2],
       [0, 4, 8, 7, 1],
       [4, 9, 3, 6, 7]])

In [101]:
# One more way to create random array
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.63847702, 0.86288872, 0.63662654],
       [0.99929706, 0.51778008, 0.32761664],
       [0.09877324, 0.5667664 , 0.21520794],
       [0.01179079, 0.29921532, 0.03897743],
       [0.97621382, 0.55145308, 0.07171621]])

In [102]:
random_array_2.shape

(5, 3)

In [103]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.34006782, 0.24290239, 0.10735082],
       [0.77033058, 0.35060155, 0.18764274],
       [0.91265269, 0.86114826, 0.39889823],
       [0.54633644, 0.45037544, 0.69359919],
       [0.21384609, 0.3237989 , 0.73989292]])

In [104]:
# Psuedo random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [105]:
random_array_4.shape

(5, 3)

In [106]:
np.random.seed(seed=7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [107]:
random_array_6 = np.random.random((5, 3))
random_array_6

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

### Viewing Arrays and Matrices

In [108]:
# Finding unique values in an array
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
np.unique(random_array_6)

array([0.02489923, 0.13316945, 0.21338535, 0.23030288, 0.45212396,
       0.46775286, 0.52341258, 0.54848992, 0.60054892, 0.66901324,
       0.75040986, 0.90912837, 0.90959353, 0.93120602, 0.9501295 ])

In [110]:
a1

array([1, 2, 3])

In [111]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [112]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [113]:
a1[0]

1

In [114]:
a2.shape

(2, 3)

In [115]:
a2[0]

array([1. , 2. , 3.3])

In [116]:
a3.shape

(2, 3, 3)

In [117]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [118]:
a2.shape, a2

((2, 3),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]))

In [119]:
a2[1]

array([4. , 5. , 6.5])

In [120]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [121]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [122]:
a3[:1, :2, :2]

array([[[1, 2],
        [4, 5]]])

In [123]:
# We will create 4 dimensional array
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]])

In [124]:
# slicing the required array from the matrix of multiple dimensions.
a4[0, 2, 0]

array([8, 6, 7, 2, 7])

In [125]:
a4.shape

(2, 3, 4, 5)

In [126]:
a4[:, :, :, :1]

array([[[[6],
         [0],
         [5],
         [1]],

        [[9],
         [3],
         [3],
         [4]],

        [[8],
         [3],
         [6],
         [4]]],


       [[[6],
         [4],
         [1],
         [5]],

        [[9],
         [5],
         [9],
         [6]],

        [[0],
         [4],
         [7],
         [5]]]])

### Manipulating and comparing arrays

##### Arithmetic

In [127]:
a1

array([1, 2, 3])

In [128]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [129]:
a1 + ones

array([2., 3., 4.])

In [130]:
a1 - ones

array([0., 1., 2.])

In [131]:
a1 * ones

array([1., 2., 3.])

In [132]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [133]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [134]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [135]:
# a2 * a3 # This will fail due to shape mismatch

In [136]:
# a2.transpose() * a3  # This will fail due to shape mismatch.

In [137]:
a1 / ones

array([1., 2., 3.])

In [138]:
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [139]:
a2.shape, a1.shape

((2, 3), (3,))

In [140]:
a2, a2 ** 2

(array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]),
 array([[ 1.  ,  4.  , 10.89],
        [16.  , 25.  , 42.25]]))

In [141]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [142]:
a1 % 2

array([1, 0, 1])

In [143]:
a1 / 2

array([0.5, 1. , 1.5])

In [144]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [145]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [146]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

##### Aggregation

Aggregation = Performing same operation on a number of things.

In [147]:
listy__list = [1, 2, 3]
type(listy__list)

list

In [148]:
sum(listy__list)  # This is a python function.

6

In [149]:
# lets use the same on array
a1

array([1, 2, 3])

In [150]:
sum(a1), np.sum(a1)

(6, 6)

Use Python's methods (`sum()`) on python datatypes and use NumPy's methods on NumPy arrays (`np.sum()`)

In [151]:
# Create a massive array to demostrate the power of numpy
massive_array = np.random.random(100000)
massive_array.size, massive_array.ndim

(100000, 1)

In [152]:
massive_array[:10]

array([0.62342345, 0.62955693, 0.9099729 , 0.96251949, 0.5850998 ,
       0.16489774, 0.39159332, 0.94455493, 0.34339118, 0.70507037])

In [153]:
# We will now time the functions on python and numpy. We use magic function %timeit for this purpose.
%timeit sum(massive_array)
%timeit np.sum(massive_array)

4.09 ms ± 37.2 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
21.4 μs ± 92.8 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [154]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [156]:
np.mean(a2)

3.6333333333333333

In [157]:
np.max(a2)

6.5

In [158]:
np.min(a2)

1.0

In [159]:
# Standard deviation = as measure of how spread out a group of numbers is from the mean.
np.std(a2)

1.8226964152656422

In [160]:
np.var(a2)
# var = measure of average degree to which each number is different to mean.
# Higher variance = Wider range of numbers.
# Lower variance = Lower range of numbers.

3.3222222222222224

In [161]:
# Standard deviation = squareroot of variance.
np.std(a2) == np.sqrt(np.var(a2))

True