#### Introduction to NumPy

In [2]:
import numpy as np

#### Datatypes and Attributes

In [3]:
## Numpy main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

In [6]:
a2.ndim

2

In [7]:
a1.ndim

1

In [8]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],

               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [9]:
a3.ndim

3

In [10]:
a3.shape

(2, 3, 3)

In [16]:
# lets create an array with shape (2, 4, 5)
test_array = np.array([[[1, 2, 3, 4, 5],
                        [6, 7, 8, 9, 1],
                        [2, 3, 4, 5, 6],
                        [7, 8, 9, 1, 2]],
                        
                        [[1, 2, 3, 4, 5],
                         [6, 7, 8, 9, 1],
                         [2, 3, 4, 5, 6],
                         [7, 8, 9, 1, 2]]])

In [17]:
test_array.ndim

3

In [18]:
test_array.shape

(2, 4, 5)

In [19]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [20]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [21]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [22]:
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (2, 3, 3))

In [23]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [24]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [26]:
# Create a pandas dataframe from numpy array
import pandas as pd

In [27]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [31]:
# df_3 = pd.DataFrame(a3)  # We cannot visualize this.

#### Creating Arrays

In [32]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [33]:
sample_array.dtype

dtype('int64')

In [38]:
ones = np.ones((2, 3, 4))
ones

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [39]:
ones.dtype

dtype('float64')

In [40]:
type(ones)

numpy.ndarray

In [41]:
zeros = np.zeros((2, 3, 4))
zeros

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [42]:
zeros.dtype

dtype('float64')

In [43]:
type(zeros)

numpy.ndarray

In [44]:
range_array = np.arange(0, 10, 2) # start stop step
range_array

array([0, 2, 4, 6, 8])

In [61]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[2, 8, 7, 7, 3],
       [4, 6, 6, 1, 5],
       [7, 1, 8, 1, 9]])

In [79]:
# One more way to create random array
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.28043425, 0.21747292, 0.43323177],
       [0.71227615, 0.93010107, 0.54666226],
       [0.45348655, 0.66284971, 0.78362137],
       [0.15323788, 0.74256077, 0.64559534],
       [0.88020846, 0.64088299, 0.67147252]])

In [80]:
random_array_2.shape

(5, 3)

In [93]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.52433468, 0.67065593, 0.76998393],
       [0.01045832, 0.98644038, 0.73144247],
       [0.16185527, 0.54528015, 0.27462331],
       [0.33462546, 0.57637001, 0.55710671],
       [0.8181684 , 0.80460605, 0.90196054]])