#### Introduction to NumPy

In [2]:
import numpy as np

#### Datatypes and Attributes

In [3]:
## Numpy main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

In [6]:
a2.ndim

2

In [7]:
a1.ndim

1

In [8]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],

               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [9]:
a3.ndim

3

In [10]:
a3.shape

(2, 3, 3)

In [11]:
# lets create an array with shape (2, 4, 5)
test_array = np.array([[[1, 2, 3, 4, 5],
                        [6, 7, 8, 9, 1],
                        [2, 3, 4, 5, 6],
                        [7, 8, 9, 1, 2]],
                        
                        [[1, 2, 3, 4, 5],
                         [6, 7, 8, 9, 1],
                         [2, 3, 4, 5, 6],
                         [7, 8, 9, 1, 2]]])

In [12]:
test_array.ndim

3

In [13]:
test_array.shape

(2, 4, 5)

In [14]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [15]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [16]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [17]:
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (2, 3, 3))

In [18]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [19]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [20]:
# Create a pandas dataframe from numpy array
import pandas as pd

In [21]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [22]:
# df_3 = pd.DataFrame(a3)  # We cannot visualize this.

#### Creating Arrays

In [23]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [24]:
sample_array.dtype

dtype('int64')

In [25]:
ones = np.ones((2, 3, 4))
ones

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [26]:
ones.dtype

dtype('float64')

In [27]:
type(ones)

numpy.ndarray

In [28]:
zeros = np.zeros((2, 3, 4))
zeros

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [29]:
zeros.dtype

dtype('float64')

In [30]:
type(zeros)

numpy.ndarray

In [31]:
range_array = np.arange(0, 10, 2) # start stop step
range_array

array([0, 2, 4, 6, 8])

In [32]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[1, 2, 6, 8, 9],
       [8, 9, 8, 1, 1],
       [5, 3, 4, 6, 0]])

In [33]:
# One more way to create random array
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.13133913, 0.9487937 , 0.28462432],
       [0.26578337, 0.07757   , 0.00537807],
       [0.18404688, 0.2822388 , 0.78332396],
       [0.90900274, 0.28496467, 0.53907295],
       [0.8664765 , 0.56011041, 0.31226721]])

In [34]:
random_array_2.shape

(5, 3)

In [35]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.06339125, 0.27124541, 0.79352211],
       [0.32358781, 0.62348178, 0.0697481 ],
       [0.41330107, 0.50307811, 0.83610687],
       [0.41127275, 0.4021101 , 0.85923494],
       [0.88940488, 0.33313581, 0.01072511]])

In [50]:
# Psuedo random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [44]:
random_array_4.shape

(5, 3)

In [53]:
np.random.seed(seed=7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [60]:
random_array_6 = np.random.random((5, 3))
random_array_6

array([[0.72816128, 0.82122761, 0.76051512],
       [0.00714328, 0.42025683, 0.46313622],
       [0.0554995 , 0.54144213, 0.60777075],
       [0.82845319, 0.94180927, 0.12814785],
       [0.23043067, 0.6591584 , 0.13247399]])

### Viewing Arrays and Matrices

In [61]:
# Finding unique values in an array
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
np.unique(random_array_6)

array([0.00714328, 0.0554995 , 0.12814785, 0.13247399, 0.23043067,
       0.42025683, 0.46313622, 0.54144213, 0.60777075, 0.6591584 ,
       0.72816128, 0.76051512, 0.82122761, 0.82845319, 0.94180927])

In [63]:
a1

array([1, 2, 3])

In [64]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [65]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [66]:
a1[0]

1

In [68]:
a2.shape

(2, 3)

In [67]:
a2[0]

array([1. , 2. , 3.3])

In [69]:
a3.shape

(2, 3, 3)

In [70]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
a2.shape, a2

((2, 3),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]))

In [73]:
a2[1]

array([4. , 5. , 6.5])

In [75]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [76]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [77]:
a3[:1, :2, :2]

array([[[1, 2],
        [4, 5]]])