#### Introduction to NumPy

In [1]:
import numpy as np

#### Datatypes and Attributes

In [2]:
## Numpy main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

In [5]:
a2.ndim

2

In [6]:
a1.ndim

1

In [7]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],

               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [8]:
a3.ndim

3

In [9]:
a3.shape

(2, 3, 3)

In [10]:
# lets create an array with shape (2, 4, 5)
test_array = np.array([[[1, 2, 3, 4, 5],
                        [6, 7, 8, 9, 1],
                        [2, 3, 4, 5, 6],
                        [7, 8, 9, 1, 2]],
                        
                        [[1, 2, 3, 4, 5],
                         [6, 7, 8, 9, 1],
                         [2, 3, 4, 5, 6],
                         [7, 8, 9, 1, 2]]])

In [11]:
test_array.ndim

3

In [12]:
test_array.shape

(2, 4, 5)

In [13]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [14]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [15]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [16]:
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (2, 3, 3))

In [17]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [18]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [19]:
# Create a pandas dataframe from numpy array
import pandas as pd

In [20]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [21]:
# df_3 = pd.DataFrame(a3)  # We cannot visualize this.

#### Creating Arrays

In [22]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [23]:
sample_array.dtype

dtype('int64')

In [24]:
ones = np.ones((2, 3, 4))
ones

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [25]:
ones.dtype

dtype('float64')

In [26]:
type(ones)

numpy.ndarray

In [27]:
zeros = np.zeros((2, 3, 4))
zeros

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [28]:
zeros.dtype

dtype('float64')

In [29]:
type(zeros)

numpy.ndarray

In [30]:
range_array = np.arange(0, 10, 2) # start stop step
range_array

array([0, 2, 4, 6, 8])

In [31]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[5, 1, 3, 6, 9],
       [3, 2, 6, 8, 5],
       [7, 5, 7, 3, 4]])

In [32]:
# One more way to create random array
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.19914725, 0.12310823, 0.62166709],
       [0.00427964, 0.58796668, 0.07453083],
       [0.60518953, 0.44980095, 0.34380831],
       [0.83088654, 0.1278202 , 0.16797831],
       [0.62070295, 0.32952688, 0.87231926]])

In [33]:
random_array_2.shape

(5, 3)

In [34]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.28099404, 0.55501668, 0.41664626],
       [0.65143553, 0.83984307, 0.8188293 ],
       [0.56746216, 0.83610699, 0.46779222],
       [0.60801698, 0.4782357 , 0.2803731 ],
       [0.15475128, 0.7817242 , 0.99590737]])