#### Introduction to NumPy

In [1]:
import numpy as np

#### Datatypes and Attributes

In [2]:
## Numpy main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

In [5]:
a2.ndim

2

In [6]:
a1.ndim

1

In [7]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],

               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [8]:
a3.ndim

3

In [9]:
a3.shape

(2, 3, 3)

In [10]:
# lets create an array with shape (2, 4, 5)
test_array = np.array([[[1, 2, 3, 4, 5],
                        [6, 7, 8, 9, 1],
                        [2, 3, 4, 5, 6],
                        [7, 8, 9, 1, 2]],
                        
                        [[1, 2, 3, 4, 5],
                         [6, 7, 8, 9, 1],
                         [2, 3, 4, 5, 6],
                         [7, 8, 9, 1, 2]]])

In [11]:
test_array.ndim

3

In [12]:
test_array.shape

(2, 4, 5)

In [13]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [14]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [15]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [16]:
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (2, 3, 3))

In [17]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [18]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [19]:
# Create a pandas dataframe from numpy array
import pandas as pd

In [20]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [21]:
# df_3 = pd.DataFrame(a3)  # We cannot visualize this.

#### Creating Arrays

In [22]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [23]:
sample_array.dtype

dtype('int64')

In [24]:
ones = np.ones((2, 3, 4))
ones

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [25]:
ones.dtype

dtype('float64')

In [26]:
type(ones)

numpy.ndarray

In [27]:
zeros = np.zeros((2, 3, 4))
zeros

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [28]:
zeros.dtype

dtype('float64')

In [29]:
type(zeros)

numpy.ndarray

In [30]:
range_array = np.arange(0, 10, 2) # start stop step
range_array

array([0, 2, 4, 6, 8])

In [31]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[0, 8, 2, 0, 1],
       [2, 9, 7, 5, 9],
       [0, 8, 7, 2, 0]])

In [32]:
# One more way to create random array
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.75099368, 0.23885129, 0.15995546],
       [0.54501489, 0.3186079 , 0.16272565],
       [0.36067099, 0.9608327 , 0.8244944 ],
       [0.39839549, 0.57880274, 0.6298607 ],
       [0.32679598, 0.67681928, 0.53832914]])

In [33]:
random_array_2.shape

(5, 3)

In [34]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.26505785, 0.8854125 , 0.56961643],
       [0.86603418, 0.20637862, 0.82111182],
       [0.80698842, 0.30133912, 0.16736867],
       [0.27055872, 0.24683139, 0.22043046],
       [0.95019374, 0.57372681, 0.95886548]])

In [35]:
# Psuedo random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [36]:
random_array_4.shape

(5, 3)

In [37]:
np.random.seed(seed=7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [38]:
random_array_6 = np.random.random((5, 3))
random_array_6

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

### Viewing Arrays and Matrices

In [39]:
# Finding unique values in an array
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.unique(random_array_6)

array([0.02489923, 0.13316945, 0.21338535, 0.23030288, 0.45212396,
       0.46775286, 0.52341258, 0.54848992, 0.60054892, 0.66901324,
       0.75040986, 0.90912837, 0.90959353, 0.93120602, 0.9501295 ])

In [41]:
a1

array([1, 2, 3])

In [42]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [43]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [44]:
a1[0]

1

In [45]:
a2.shape

(2, 3)

In [46]:
a2[0]

array([1. , 2. , 3.3])

In [47]:
a3.shape

(2, 3, 3)

In [48]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
a2.shape, a2

((2, 3),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]))

In [50]:
a2[1]

array([4. , 5. , 6.5])

In [51]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [52]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [53]:
a3[:1, :2, :2]

array([[[1, 2],
        [4, 5]]])

In [54]:
# We will create 4 dimensional array
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]])

In [55]:
# slicing the required array from the matrix of multiple dimensions.
a4[0, 2, 0]

array([8, 6, 7, 2, 7])

In [56]:
a4.shape

(2, 3, 4, 5)

In [57]:
a4[:, :, :, :1]

array([[[[6],
         [0],
         [5],
         [1]],

        [[9],
         [3],
         [3],
         [4]],

        [[8],
         [3],
         [6],
         [4]]],


       [[[6],
         [4],
         [1],
         [5]],

        [[9],
         [5],
         [9],
         [6]],

        [[0],
         [4],
         [7],
         [5]]]])

### Manipulating and comparing arrays

##### Arithmetic

In [58]:
a1

array([1, 2, 3])

In [59]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [60]:
a1 + ones

array([2., 3., 4.])

In [61]:
a1 - ones

array([0., 1., 2.])

In [62]:
a1 * ones

array([1., 2., 3.])

In [63]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [64]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [65]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [66]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [69]:
a2.transpose() * a3

ValueError: operands could not be broadcast together with shapes (3,2) (2,3,3) 

In [70]:
a1 / ones

array([1., 2., 3.])

In [71]:
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [72]:
a2.shape, a1.shape

((2, 3), (3,))

In [74]:
a2, a2 ** 2

(array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]),
 array([[ 1.  ,  4.  , 10.89],
        [16.  , 25.  , 42.25]]))

In [76]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [77]:
a1 % 2

array([1, 0, 1])

In [78]:
a1 / 2

array([0.5, 1. , 1.5])

In [79]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [80]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [81]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])