In [1]:
import numpy as np

In [14]:
# generating 2 random matrices and equating them.

np.random.seed(seed=10)
array_1 = np.random.randint(1, 11, size=(5, 3))
array_1

array([[10,  5,  1],
       [ 2, 10,  1],
       [ 2,  9, 10],
       [ 1,  9,  7],
       [ 5,  4,  1]])

In [16]:
np.random.seed(seed=10)
array_2 = np.random.randint(1, 11, size=(5, 3))
array_2

array([[10,  5,  1],
       [ 2, 10,  1],
       [ 2,  9, 10],
       [ 1,  9,  7],
       [ 5,  4,  1]])

In [17]:
array_1 == array_2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [26]:
# experimenting on the same cell.
np.random.seed(seed=13)
array_3 = np.random.randint(3, 33, size=(5, 4))
np.random.seed(seed=13)
array_4 = np.random.randint(3, 33, size=(5, 4))
array_3 == array_4

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])