In [1]:
import numpy as np

In [2]:
# generating 2 random matrices and equating them.

np.random.seed(seed=10)
array_1 = np.random.randint(1, 11, size=(5, 3))
array_1

array([[10,  5,  1],
       [ 2, 10,  1],
       [ 2,  9, 10],
       [ 1,  9,  7],
       [ 5,  4,  1]])

In [3]:
np.random.seed(seed=10)
array_2 = np.random.randint(1, 11, size=(5, 3))
array_2

array([[10,  5,  1],
       [ 2, 10,  1],
       [ 2,  9, 10],
       [ 1,  9,  7],
       [ 5,  4,  1]])

In [4]:
array_1 == array_2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [5]:
# experimenting on the same cell.
np.random.seed(seed=13)
array_3 = np.random.randint(3, 33, size=(5, 4))
np.random.seed(seed=13)
array_4 = np.random.randint(3, 33, size=(5, 4))
array_3 == array_4

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

#### Slicing arrays

In [11]:
# Create a 4D array in the range of (5, 25) with shape (4, 5, 6, 7). Set seed to 12 for reproducability.
np.random.seed(12)
arr_4d_1 = np.random.randint(5, 25, size=(4, 5, 6, 7))
arr_4d_1

array([[[[16, 11, 22,  7,  8,  8, 17],
         [21, 22, 10, 18,  7, 16, 15],
         [ 5, 13, 17, 18, 23,  8,  9],
         [ 8,  6,  5, 23, 23, 21, 11],
         [18, 14, 18, 21,  5, 19, 20],
         [ 6,  9,  5,  9,  6, 16, 17]],

        [[10, 16, 24,  9, 16, 16, 20],
         [ 5, 15, 11, 11, 18,  8,  7],
         [15,  8, 16, 18,  6, 14, 10],
         [24, 16,  5, 16, 23, 18, 11],
         [23, 24,  7, 11,  9,  5, 21],
         [10, 21,  8, 18, 11, 20,  6]],

        [[ 9, 17, 10, 15, 14,  7,  9],
         [21, 17,  9,  8, 12, 24, 22],
         [ 9, 19, 15, 17, 24, 13, 13],
         [14, 19,  9, 20,  9,  6, 22],
         [16,  9, 24, 23, 16, 17,  5],
         [ 6,  9, 11, 10,  7, 15,  5]],

        [[22,  7, 15, 23, 21, 22, 15],
         [12, 12, 22, 11, 22,  8, 20],
         [ 5,  6, 17, 18, 13, 13, 13],
         [20, 17, 20, 24, 14, 19, 16],
         [20, 19, 10,  6, 20, 24, 23],
         [24, 22, 24,  7,  7, 20, 19]],

        [[13, 14, 24, 10,  6,  9, 18],
         [21, 19,

In [14]:
arr_4d_1.shape, arr_4d_1.ndim

((4, 5, 6, 7), 4)

In [17]:
arr_4d_1[0, 0].ndim

2

In [23]:
# Lets extract [14, 14, 10, 14, 18, 23,  5] from the matrix.
arr_4d_1[-1, 1, 0, :]

array([14, 14, 10, 14, 18, 23,  5])

In [24]:
# We will now extract the last quadrant of each matric in this 4d matrix.
arr_4d_1.shape

(4, 5, 6, 7)

In [29]:
arr_4d_1[:, :, 4:, 5:]

array([[[[19, 20],
         [16, 17]],

        [[ 5, 21],
         [20,  6]],

        [[17,  5],
         [15,  5]],

        [[24, 23],
         [20, 19]],

        [[19, 18],
         [ 5, 11]]],


       [[[13, 11],
         [24,  8]],

        [[24, 18],
         [12, 12]],

        [[13, 12],
         [12, 15]],

        [[18, 17],
         [13, 21]],

        [[10, 14],
         [22,  9]]],


       [[[21, 14],
         [11,  8]],

        [[14, 22],
         [12, 16]],

        [[24, 22],
         [16, 20]],

        [[ 6, 12],
         [ 5, 24]],

        [[12,  9],
         [18, 11]]],


       [[[ 5, 13],
         [22,  8]],

        [[19,  7],
         [21, 19]],

        [[13, 22],
         [ 8, 21]],

        [[17, 17],
         [18, 16]],

        [[ 5, 15],
         [ 5, 19]]]])